//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsgD2._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citation
    {
        public int CitationNumber { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<int> BadgeNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Description { get; set; }
    }
}
